:stem:

= Множества и операции над ними. Булевы функции, КНФ, ДНФ. Базисы, теорема Поста.

https://old.mccme.ru//free-books/shen/shen-logic-part1-5ed.pdf[Н. К. Верещагин, А. Шень. Лекции по математической логике и теории алгоритмов. Часть 1]

== Множества и операции над ними

* Множества состоят из элементов. Запись 𝑥 ∈ 𝑀 означает,
что 𝑥 является элементом множества 𝑀 .

* Говорят, что множество 𝐴 является подмножеством множества 𝐵 (запись: 𝐴 ⊂ 𝐵), если все элементы 𝐴 являются элементами 𝐵.

* Множества 𝐴 и 𝐵 равны (запись: 𝐴 = 𝐵), если они содержат
одни и те же элементы (другими словами, если 𝐴 ⊂ 𝐵 и 𝐵 ⊂ 𝐴).

* Если 𝐴 — подмножество 𝐵, не равное всему 𝐵, то 𝐴 называют
собственным подмножеством 𝐵.

* Пустое множество ∅ не содержит ни одного элемента и является подмножеством любого множества.

* Пересечение 𝐴 ∩ 𝐵 двух множеств 𝐴 и 𝐵 состоит из элементов,
которые принадлежат обоим множествам 𝐴 и 𝐵. Это записывают так:
𝐴 ∩ 𝐵 = {𝑥 | 𝑥 ∈ 𝐴 и 𝑥 ∈ 𝐵}
(читается: множество таких 𝑥, что . . . ).

* Объединение 𝐴∪𝐵 состоит из элементов, которые принадлежат
хотя бы одному из множеств 𝐴 и 𝐵:
𝐴 ∪ 𝐵 = {𝑥 | 𝑥 ∈ 𝐴 или 𝑥 ∈ 𝐵}.

* Разность 𝐴∖𝐵 состоит из элементов, которые принадлежат 𝐴,
но не принадлежат 𝐵:
𝐴 ∖ 𝐵 = {𝑥 | 𝑥 ∈ 𝐴 и 𝑥 /∈ 𝐵}.
Если множество 𝐵 является подмножеством множества 𝐴, разность 𝐴 ∖ 𝐵 называют также дополнением 𝐵 до 𝐴.

* Симметрическая разность 𝐴 △ 𝐵 состоит из элементов, которые принадлежат ровно одному из множеств 𝐴 и 𝐵:
𝐴 △ 𝐵 = (𝐴 ∖ 𝐵) ∪ (𝐵 ∖ 𝐴) = (𝐴 ∪ 𝐵) ∖ (𝐴 ∩ 𝐵).

* Через {𝑎, 𝑏, 𝑐} обозначается множество, которое содержит элементы 𝑎, 𝑏, 𝑐 и не содержит других. Если среди 𝑎, 𝑏, 𝑐 есть равные, оно может содержать один или два элемента. Подобное
обозначение используется и в менее формальных ситуациях:
множество членов последовательности 𝑎0, 𝑎1, . . . обозначается
{𝑎0, 𝑎1, . . .} или даже {𝑎𝑖}. Более аккуратная запись для того
же множества такова: {𝑎𝑖 | 𝑖 ∈ N}, где N — множество натуральных чисел {0, 1, 2, . . .}.


Перечислимые множества 