:stem:

= ะัะฝะพัะตะฝะธั ะธ ััะฝะบัะธะธ.

ะัะฝะพัะตะฝะธั ะธ ััะฝะบัะธะธ. ะัะฝะพัะตะฝะธะต ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ ะธ ัะฐะทะฑะธะตะฝะธั. ะคะฐะบัะพั ะผะฝะพะถะตััะฒะฐ. ะัะฝะพัะตะฝะธั ัะฐััะธัะฝะพะณะพ ะฟะพััะดะบะฐ.


ะัััั ๐ด ะธ ๐ต โ ะดะฒะฐ ะผะฝะพะถะตััะฒะฐ. ะะฐััะผะพััะธะผ ะผะฝะพะถะตััะฒะพ ะฒัะตั *ัะฟะพััะดะพัะตะฝะฝัั* ะฟะฐั โจ๐, ๐โฉ, ะณะดะต ๐ โ ๐ด ะธ ๐ โ ๐ต. ะญัะพ ะผะฝะพะถะตััะฒะพ ะฝะฐะทัะฒะฐะตััั #ะดะตะบะฐััะพะฒัะผ ะฟัะพะธะทะฒะตะดะตะฝะธะตะผ# ะผะฝะพะถะตััะฒ ๐ด ะธ ๐ต ะธ ะพะฑะพะทะฝะฐัะฐะตััั ๐ด ร ๐ต.

ะัะฑะพะต ะฟะพะดะผะฝะพะถะตััะฒะพ ๐ ะผะฝะพะถะตััะฒะฐ ๐ด ร ๐ต ะฝะฐะทัะฒะฐะตััั #ะพัะฝะพัะตะฝะธะตะผ# ะผะตะถะดั ะผะฝะพะถะตััะฒะฐะผะธ ๐ด ะธ ๐ต. ะัะปะธ ๐ด = ๐ต, ะณะพะฒะพััั ะพ #ะฑะธะฝะฐัะฝะพะผ
ะพัะฝะพัะตะฝะธะธ# ะฝะฐ ะผะฝะพะถะตััะฒะต ๐ด. ะะฐะฟัะธะผะตั, ะพัะฝะพัะตะฝะธะต "ะฑััั ะดะตะปะธัะตะปะตะผ |" โจ2, 6โฉ โ | ะธ โจ2, 7โฉ stem:[\notin] | ะธะปะธ 2|6.

ะัะฝะพัะตะฝะธะต ๐น โ ๐ด ร ๐ต ะฝะฐะทัะฒะฐะตััั #ััะฝะบัะธะตะน# ะธะท ๐ด ะฒ ๐ต, ะตัะปะธ ะพะฝะพ ะฝะต ัะพะดะตัะถะธั ะฟะฐั ั ะพะดะธะฝะฐะบะพะฒัะผ ะฟะตัะฒัะผ ัะปะตะฝะพะผ ะธ ัะฐะทะฝัะผะธ ะฒัะพััะผะธ.


ะััะณะธะผะธ ัะปะพะฒะฐะผะธ, ััะพ ะพะทะฝะฐัะฐะตั, ััะพ ะดะปั ะบะฐะถะดะพะณะพ ๐ โ ๐ด ัััะตััะฒัะตั
ะฝะต ะฑะพะปะตะต ะพะดะฝะพะณะพ ๐ โ ๐ต, ะฟัะธ ะบะพัะพัะพะผ โจ๐, ๐โฉ โ ๐น .
ะขะต ัะปะตะผะตะฝัั ๐ โ ๐ด, ะดะปั ะบะพัะพััั ัะฐะบะพะต ๐ ัััะตััะฒัะตั, ะพะฑัะฐะทััั
ะพะฑะปะฐััั #ะพะฟัะตะดะตะปะตะฝะธั ััะฝะบัะธะธ# ๐น . ะะฝะฐ ะพะฑะพะทะฝะฐัะฐะตััั Dom ๐น (ะพั ะฐะฝะณะปะธะนัะบะพะณะพ ัะปะพะฒะฐ domain). ะะปั ะปัะฑะพะณะพ ัะปะตะผะตะฝัะฐ ๐ โ Dom ๐น ะผะพะถะฝะพ
ะพะฟัะตะดะตะปะธัั ะทะฝะฐัะตะฝะธะต ััะฝะบัะธะธ ๐น ะฝะฐ ะฐัะณัะผะตะฝัะต ๐ (ยซะฒ ัะพัะบะต ๐ยป, ะบะฐะบ
ะธะฝะพะณะดะฐ ะณะพะฒะพััั) ะบะฐะบ ัะพั ะตะดะธะฝััะฒะตะฝะฝัะน ัะปะตะผะตะฝั ๐ โ ๐ต, ะดะปั ะบะพัะพัะพะณะพ
โจ๐, ๐โฉ โ ๐น . ะญัะพั ัะปะตะผะตะฝั ะทะฐะฟะธััะฒะฐัั ะบะฐะบ ๐น (๐). ะัะต ัะฐะบะธะต ัะปะตะผะตะฝัั ๐
ะพะฑัะฐะทััั #ะผะฝะพะถะตััะฒะพ ะทะฝะฐัะตะฝะธะน# ััะฝะบัะธะธ ๐น , ะบะพัะพัะพะต ะพะฑะพะทะฝะฐัะฐะตััั
Val ๐น .

ะัะปะธ ะพะฑะปะฐััั ะพะฟัะตะดะตะปะตะฝะธั ััะฝะบัะธะธ ๐ ะธะท ๐ด ะฒ ๐ต ัะพะฒะฟะฐะดะฐะตั ั ๐ด, ัะพ
ะฟะธััั ๐ : ๐ด โ ๐ต.

== ะัะฝะพัะตะฝะธะต ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ 

ะะธะฝะฐัะฝะพะต ะพัะฝะพัะตะฝะธะต ๐ ะฝะฐ ะผะฝะพะถะตััะฒะต ๐ ะฝะฐะทัะฒะฐะตััั ะพัะฝะพัะตะฝะธะตะผ
ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ, ะตัะปะธ ะฒัะฟะพะปะฝะตะฝั ัะปะตะดัััะธะต ัะฒะพะนััะฒะฐ

โ (ัะตัะปะตะบัะธะฒะฝะพััั) ๐ฅ๐๐ฅ ะดะปั ะฒัะตั ๐ฅ โ ๐;
โ (ัะธะผะผะตััะธัะฝะพััั) ๐ฅ๐๐ฆ โ ๐ฆ๐๐ฅ ะดะปั ะฒัะตั ๐ฅ, ๐ฆ โ ๐;
โ (ััะฐะฝะทะธัะธะฒะฝะพััั) ๐ฅ๐๐ฆ ะธ ๐ฆ๐๐ง โ ๐ฅ๐๐ง ะดะปั ะฒัะตั ๐ฅ, ๐ฆ, ๐ง โ ๐


 ะัะปะธ ะผะฝะพะถะตััะฒะพ ๐ ัะฐะทะฑะธัะพ ะฒ ะพะฑัะตะดะธะฝะตะฝะธะต ะฝะตะฟะตัะตัะตะบะฐััะธััั ะฟะพะดะผะฝะพะถะตััะฒ, ัะพ ะพัะฝะพัะตะฝะธะต ยซะปะตะถะฐัั ะฒ ะพะดะฝะพะผ ะฟะพะดะผะฝะพะถะตััะฒะตยป ัะฒะปัะตััั ะพัะฝะพัะตะฝะธะตะผ ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ.

ะะปั ัะปะตะผะตะฝัะฐ ๐ฅ โ ๐ ะบะปะฐัั ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ โ ะผะฝะพะถะตััะฒะพ ะฒัะตั ๐ฆ โ ๐, ะดะปั ะบะพัะพััั ะฒะตัะฝะพ ๐ฅ๐๐ฆ.

== ะัะฝะพัะตะฝะธะต ัะฐะทะฑะธะตะฝะธั 

== ะคะฐะบัะพั ะผะฝะพะถะตััะฒะฐ

ะะฝะพะถะตััะฒะพ ะบะปะฐััะพะฒ ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ ะฝะฐะทัะฒะฐัั #ัะฐะบัะพั-ะผะฝะพะถะตััะฒะพะผ# ะผะฝะพะถะตััะฒะฐ ๐ ะฟะพ ะพัะฝะพัะตะฝะธั ัะบะฒะธะฒะฐะปะตะฝัะฝะพััะธ ๐. 

 ะัะปะธ ะพัะฝะพัะตะฝะธะต ัะพะณะปะฐัะพะฒะฐะฝะพ ั ะดะพะฟะพะปะฝะธัะตะปัะฝัะผะธ ััััะบัััะฐะผะธ ะฝะฐ ๐, ะฟะพะปััะฐัััั ัะฐะบัะพั-ะณััะฟะฟั, ัะฐะบัะพั-ะบะพะปััะฐ ะธ ั. ะด.

== ะัะฝะพัะตะฝะธั ัะฐััะธัะฝะพะณะพ ะฟะพััะดะบะฐ โค

ะะธะฝะฐัะฝะพะต ะพัะฝะพัะตะฝะธะต 6 ะฝะฐ ะผะฝะพะถะตััะฒะต ๐ ะฝะฐะทัะฒะฐะตััั ะพัะฝะพัะตะฝะธะตะผ
ัะฐััะธัะฝะพะณะพ ะฟะพััะดะบะฐ, ะตัะปะธ ะฒัะฟะพะปะฝะตะฝั ัะฐะบะธะต ัะฒะพะนััะฒะฐ:
โ (ัะตัะปะตะบัะธะฒะฝะพััั) ๐ฅ โค ๐ฅ ะดะปั ะฒัะตั ๐ฅ โ ๐;
โ (ะฐะฝัะธัะธะผะผะตััะธัะฝะพััั) ๐ฅ โค ๐ฆ ะธ ๐ฆ โค ๐ฅ โ ๐ฅ = ๐ฆ
ะดะปั ะฒัะตั ๐ฅ, ๐ฆ โ ๐;
โ (ััะฐะฝะทะธัะธะฒะฝะพััั) ๐ฅ โค ๐ฆ ะธ ๐ฆ โค ๐ง โ ๐ฅ โค ๐ง ะดะปั ะฒัะตั ๐ฅ, ๐ฆ, ๐ง โ ๐

 ะะฝะพะถะตััะฒะพ ั ะทะฐะดะฐะฝะฝัะผ ะฝะฐ ะฝัะผ ะพัะฝะพัะตะฝะธะตะผ ัะฐััะธัะฝะพะณะพ ะฟะพััะดะบะฐ ะฝะฐะทัะฒะฐัั #ัะฐััะธัะฝะพ ัะฟะพััะดะพัะตะฝะฝัะผ#.

ะะฒะฐ ัะปะตะผะตะฝัะฐ ๐ฅ, ๐ฆ ัะฐััะธัะฝะพ ัะฟะพััะดะพัะตะฝะฝะพะณะพ ะผะฝะพะถะตััะฒะฐ #ััะฐะฒะฝะธะผั#, ะตัะปะธ ๐ฅ โค ๐ฆ ะธะปะธ ๐ฆ โค ๐ฅ. ะะฐะผะตัะธะผ, ััะพ ะพะฟัะตะดะตะปะตะฝะธะต ัะฐััะธัะฝะพะณะพ ะฟะพััะดะบะฐ ะฝะต ััะตะฑัะตั, ััะพะฑั ะปัะฑัะต ะดะฒะฐ ัะปะตะผะตะฝัะฐ ะผะฝะพะถะตััะฒะฐ
ะฑัะปะธ ััะฐะฒะฝะธะผั. ะะพะฑะฐะฒะธะฒ ััะพ ััะตะฑะพะฒะฐะฝะธะต, ะผั ะฟะพะปััะธะผ ะพะฟัะตะดะตะปะตะฝะธะต
#ะปะธะฝะตะนะฝะพะณะพ ะฟะพััะดะบะฐ# (ะปะธะฝะตะนะฝะพ ัะฟะพััะดะพัะตะฝะฝะพะณะพ ะผะฝะพะถะตััะฒะฐ).

 ะะฐ ะผะฝะพะถะตััะฒะต R ร R ะฒัะตั ะฟะฐั ะดะตะนััะฒะธัะตะปัะฝัั ัะธัะตะป ะผะพะถะฝะพ
ะฒะฒะตััะธ ัะฐััะธัะฝัะน ะฟะพััะดะพะบ, ััะธัะฐั, ััะพ โจ๐ฅ1, ๐ฅ2โฉ โค
 โจ๐ฆ1, ๐ฆ2โฉ, ะตัะปะธ
๐ฅ1 โค ๐ฆ1 ะธ ๐ฅ2 โค ๐ฆ2. ะญัะพั ะฟะพััะดะพะบ ัะถะต ะฝะต ะฑัะดะตั ะปะธะฝะตะนะฝัะผ: ะฟะฐัั
โจ0, 1โฉ ะธ โจ1, 0โฉ ะฝะต ััะฐะฒะฝะธะผั.