= Алгоритмы на графах.
:stem:

Обходы графов. Кратчайшие пути, семейство алгоритмов A*. Остовные деревья. Задача о максимальном потоке, о паросочетании, о потоке минимальной стоимости.

== Обходы графов footnote:[https://neerc.ifmo.ru/wiki/index.php?title=Категория:Обходы_графов]



=== Обход в глубину. 
Этот метод состоит в том, чтобы идти «вглубь» графа насколько это возможно, а достигнув тупика, возвращаться к ближайшей вершине, у которой есть смежные ранее не посещённые вершины.

Оценим время работы обхода в глубину. Процедура dfs
 вызывается от каждой вершины не более одного раза, а внутри процедуры рассматриваются все такие ребра {e | begin(e)=u}
. Всего таких ребер для всех вершин в графе O(E)
, следовательно, время работы алгоритма оценивается как O(V+E)
.

=== Обход в ширину. 
Этот алгоритм заключается в том, что у нас есть некоторая текущая вершина, с которой мы все смежные, непройденные вершины заносим в очередь и выбираем следующий элемент (который хранится первым в очереди), чтобы его сделать текущим.

Оценим время работы для входного графа G=(V,E)
, где множество ребер E
 представлено списком смежности. В очередь добавляются только непосещенные вершины, поэтому каждая вершина посещается не более одного раза. Операции внесения в очередь и удаления из нее требуют O(1)
 времени, так что общее время работы с очередью составляет O(|V|)
 операций. Для каждой вершины v
 рассматривается не более deg(v)
 ребер, инцидентных ей. Так как ∑v∈Vdeg(v)=2|E|
, то время, используемое на работу с ребрами, составляет O(|E|)
. Поэтому общее время работы алгоритма поиска в ширину — O(|V|+|E|)
.

== Кратчайшие пути, семейство алгоритмов A* footnote:[https://habr.com/ru/companies/otus/articles/748470/]

Путь в графе — это последовательность вершин, в которой каждая вершина связана с следующей вершиной в последовательности ребром. Длина пути обычно в зависимости от задачи определяется как сумма весов всех ребер в пути в взвешенном графе, или просто количество ребер в пути в невзвешенном графе.

=== Алгоритм Дейкстры
используется для поиска кратчайшего пути в взвешенном графе от одной вершины (обозначим ее как начальную) до всех остальных вершин

Инициализируются два множества:

* Множество, содержащее уже обработанные вершины (изначально пустое).

* Множество, содержащее все остальные вершины графа (изначально содержит все вершины графа).

Также каждой вершине графа присваивается вес, который представляет минимальную известную стоимость пути от начальной вершины до данной. Для начальной вершины этот вес равен 0, для всех остальных вершин — бесконечность.

На каждом шаге алгоритм выбирает вершину из непосещенного множества с наименьшим весом, перемещает эту вершину в множество посещенных вершин и обновляет веса всех соседей выбранной вершины. Вес соседа обновляется, если через выбранную вершину можно добраться до этого соседа с меньшей стоимостью.

Процесс продолжается, пока не будут посещены все вершины или пока мы не найдем путь до конечной вершины (если она задана).

=== Семейство алгоритмов A* footnote:[https://neerc.ifmo.ru/wiki/index.php?title=Алгоритм_A*&mobileaction=toggle_view_mobile]

Алгоритм А* (англ. A star) — алгоритм поиска по первому наилучшему совпадению, который находит во взвешенном графе маршрут наименьшей стоимости от начальной вершины s до выбранной конечной x.

В процессе работы алгоритма для вершин рассчитывается функция f(v)=g(v)+h(v), где

* g(v) — наименьшая стоимость пути в v из стартовой вершины s,

* h(v) — эвристическое приближение стоимости пути от v до конечной цели d. Функция h(x) должна быть допустимой эвристической оценкой, то есть не должна переоценивать расстояния к целевой вершине. Например, для задачи маршрутизации h(x) может представлять собой расстояние до цели по прямой линии, так как это физически наименьшее возможное расстояние между двумя точками.

Фактически, функция f(v)
 — длина пути до цели, которая складывается из пройденного расстояния g(v)
 и оставшегося расстояния h(v). 

Исходя из этого, чем меньше значение f(v), тем раньше мы откроем вершину v
, так как через неё мы предположительно достигнем расстояние до цели d быстрее всего. Открытые алгоритмом вершины можно хранить в очереди с приоритетом по значению f(v).

А* действует подобно алгоритму Дейкстры и просматривает среди всех маршрутов ведущих к цели сначала те, которые благодаря имеющейся информации (эвристическая функция) в данный момент являются наилучшими.


