= Алгоритмы на графах.
:stem:

Обходы графов. Кратчайшие пути, семейство алгоритмов A*. Остовные деревья. Задача о максимальном потоке, о паросочетании, о потоке минимальной стоимости.

== Обходы графов footnote:[https://neerc.ifmo.ru/wiki/index.php?title=Категория:Обходы_графов]

=== Обход в глубину. 
Этот метод состоит в том, чтобы идти «вглубь» графа насколько это возможно, а достигнув тупика, возвращаться к ближайшей вершине, у которой есть смежные ранее не посещённые вершины.

Оценим время работы обхода в глубину. Процедура dfs
 вызывается от каждой вершины не более одного раза, а внутри процедуры рассматриваются все такие ребра {e | begin(e)=u}
. Всего таких ребер для всех вершин в графе O(E)
, следовательно, время работы алгоритма оценивается как O(V+E)
.

=== Обход в ширину. 
Этот алгоритм заключается в том, что у нас есть некоторая текущая вершина, с которой мы все смежные, непройденные вершины заносим в очередь и выбираем следующий элемент (который хранится первым в очереди), чтобы его сделать текущим.

Оценим время работы для входного графа G=(V,E)
, где множество ребер E
 представлено списком смежности. В очередь добавляются только непосещенные вершины, поэтому каждая вершина посещается не более одного раза. Операции внесения в очередь и удаления из нее требуют O(1)
 времени, так что общее время работы с очередью составляет O(|V|)
 операций. Для каждой вершины v
 рассматривается не более deg(v)
 ребер, инцидентных ей. Так как ∑v∈Vdeg(v)=2|E|
, то время, используемое на работу с ребрами, составляет O(|E|)
. Поэтому общее время работы алгоритма поиска в ширину — O(|V|+|E|)
.

== Кратчайшие пути, семейство алгоритмов A* footnote[https://habr.com/ru/companies/otus/articles/748470/]
