:stem:

= Формальные языки

== Формальные языки и способы их описания

Формальная грамматика - способ описания формального языка, представляющий собой четверку \$ \langle \Sigma, N, S \in N, P \subset ((\Sigma \cup N)^\star N (\Sigma \cup N)^\star) \times (\Sigma \cup N)^\star \rangle\$, где:

* \$\Sigma\$ - терминалы
* \$N\$ - нетерминалы
* \$S\$ - начальный символ
* \$P\$ - набор правил вывода

== Классификация формальных грамматик

Иерархия Хомского:

* Класс 0 - рекурсивно перечислимые языки
+
Наиболее общий класс, к которому относятся все формальные грамматики. Все правила в них записываются в виде \$\alpha \rightarrow \beta\$.

* Класс 1
+
Языки, заданные этими грамматиками, распознаются с помощью линейно ограниченного автомата (недетерминированная машина Тьюринга, чья лента ограничена константой, зависящей от длины входа). Неукорачивающие и контекстно-свободные грамматики эквивалентны.
+
** неукорачивающие грамматики - такие, что левая часть каждого их правила не короче правой. Правило \$S \rightarrow \varepsilon\$ допустимо только если \$S\$ (стартовый символ) не встречается в правых частях правил.
** контекстно-зависимые грамматики - такие, всякое правило которых имеет вид \$\alpha A \beta \rightarrow \alpha \gamma \beta \$, где \$\alpha, \beta \in {\Sigma \cup N}^*, \gamma \in {\Sigma \cup N}^+\$, правило \$S \rightarrow \varepsilon\$ также допустимо только если \$S\$ (стартовый символ) не встречается в правых частях правил.

* Класс 2 - контекстно-свободные грамматики - такие, которые допускают появление в левой части правила только одного нетерминального символа - все правила которых имеют вид \$A \rightarrow \beta\$, где \$A \in N, \beta \in {\Sigma \cup N}^+\$.

* Класс 3 - регулярные (автоматные) грамматики
+
** леволинейные грамматики - такие, все правила которых имеют вид \$A \rightarrow B \gamma\$ или \$A \rightarrow \gamma\$, где \$\gamma \in Sigma, A, B \in N\$.
** праволинейные грамматики - такие, все правила которых имеют вид \$A \rightarrow \gama B\$ или \$A \rightarrow \gamma\$, где \$\gamma \in Sigma, A, B \in N\$.
