:stem:

= Основы комбинаторного анализа.

== Метод производящих функций

*TODO*

== Метод включений и исключений

Объединение двух множеств \$A\$ и \$B\$ имеет вид: \$ |A \cup B| = |A| + |B| - |A \cap B| \$.

В случае произвольного числа множеств сначала суммируем мощности всех множеств, затем вычитаем мощности всех попарных пересечений, затем прибавляем мощности всех тройных пересечений и т. д.

https://mathus.ru/math/ief.pdf[подробное описание и доказательство]

== Генерация и перечисление комбинаторных объектов

Комбинаторные объекты — это конечные множества, на элементы которых могут накладываться определённые ограничения, такие как: различимость или неразличимость элементов, возможность повторения одинаковых элементов и т. п.

Некоторые примеры комбинаторных объектов:

- битовые векторы
- перестановки (с повторением и без)
- размещения (с повторениями и без)
- сочетания (с повторениями и без)

Для генерации комбинаторных объектов необходимо:

1. установить порядок на элементах перечисляемого множества (в частности определить первый из них);
2. научиться переходить от произвольного элемента к следующему.

Комбинаторные объекты сгенерированы в лексикографическом порядке, если для любых \$i < j\$ выполняется \$S_i < S_j\$.

Алгоритм получения следующего объекта в лексикографическом порядке:

- находим кратчайший суффикс, который можно изменить без изменения префикса текущего объекта
- к оставшейся части дописываем максимально возможный элемент, чтобы порядок выполнялся
- дописываем максимально возможный хвост

https://neerc.ifmo.ru/wiki/index.php?title=%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D1%8B%D0%B4%D1%83%D1%89%D0%B5%D0%B3%D0%BE_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0#.D0.90.D0.BB.D0.B3.D0.BE.D1.80.D0.B8.D1.82.D0.BC[примеры специализации этого алгоритма для генерации различных комбинаторных объектов]