:stem:

= Вычислительная геометрия на плоскости

== Уравнения точек, прямых, окружностей

=== Уравнения прямой
- Общее уравнение прямой: \$Ax + By + C = 0, A \ne 0, B \ne 0\$. Вектор (A, B) называется нормальным вектором, он перпендикулярен прямой.
- Уравнение прямой с угловым коэффициентом: \$y = kx + b, k = \tg \varphi\$.
В этом виде невозможно задать прямую, параллельную оси абсцисс, потому что угловой коэффициент обращается в бесконечность.
- Уравнение прямой в отрезках (задает прямую, пересекающую ось абсцисс в точке a и ось ординат в точке b): \$\frac{x}{a} + \frac{y}{b}, a \ne 0, b \ne 0\$.
- Нормальное уравнение прямой: \$x \cos \theta + y \sin \theta − p = 0\$, где p  — длина перпендикуляра, опущенного на прямую из начала координат, \$\theta\$ — угол между положительным направлением оси абсцисс и направлением этого перпендикуляра.
- Уравнение прямой, проходящей через две точки: \$(y_1 - y_2)x + (x_2 - x_1) + (x_1y_2 - x_2y_1) = 0\$
- Параметрические уравнения прямой: \$x = x_0 + a_x t; \quad y = y_0 + a_y t\$, где \$(a_x, a_y)\$ - направляющий вектор.
- Каноническое уравнение прямой (получается из параметрических уравнений делением одного на другое): \$frac{x - x_0}{a_1} = \frac{y - y_0}{a_2}\$
- Уравнение прямой в полярны координатах \$\rho\$ и \$\phi\$: \$\rho (A \cos \phi + B \sin \phi) + C) = 0\$

=== Уравнение окружности
- Общее уравнение окружности: \$(x - a)^2 + (y - b)^2 = R^2\$, \$(a, b)\$ - центр, \$R\$ - радиус окружности.
- Параметрические уравнения окружности: \$x = x_0 + R \cos \varphi; \quad y = y_0 + R \sin \varphi\$
- Уравнение окружности в полярных координатах: \$ \rho^2 - 2 \rho \rho_0 \cos(\phi - \phi_0) + \rho_0^2 = R^2 \$

== Выпуклые оболочки, алгоритмы построения

Выпуклое множество — такое множество точек, что, для любых двух точек множества, все точки на отрезке между ними тоже принадлежат этому множеству.
Выпуклая оболочка множества точек — такое выпуклое множество точек, что все точки фигуры также лежат в нем.

Для практических целей выпуклые оболочки полезны тем, что они компактно хранят всю необходимую информацию о множестве точек, что позволяет быстро отвечать на разнообразные запросы на этом множестве.
https://ru.algorithmica.org/cs/convex-hulls/hull-applications:[Подробнее о применениях выпуклых оболочек]

=== Алгоритм Джарвиса (алгоритм заворачивания подарка)
Идея в том, чтобы сначала выбрать точку, которая точно принадлежит выпуклой оболочке, например самую правую, а потом добавлять самую правую точку от предыдущей, пока оболочка не замкнется.
Асимптотика \$ O(nh) \$, где \$h\$ - точки выпуклой оболочки. В худшем случае (когда все точки принадлежат оболочке) - \$O(n^2)\$
Корректность доказывается по индукции.

https://ru.algorithmica.org/cs/convex-hulls/jarvis/[подробное описание]

=== Сканирование Грэхема
Оптимизация алгоритм Джарвиса при которой точки сначала сортируются по полярному углу относительно начальной.
Асимптотика \$O(n \log n)\$

https://ru.algorithmica.org/cs/convex-hulls/graham/[подробное описание]

https://neerc.ifmo.ru/wiki/index.php?title=%D0%A1%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B2%D1%8B%D0%BF%D1%83%D0%BA%D0%BB%D1%8B%D0%B5_%D0%BE%D0%B1%D0%BE%D0%BB%D0%BE%D1%87%D0%BA%D0%B8:_%D0%94%D0%B6%D0%B0%D1%80%D0%B2%D0%B8%D1%81,_%D0%93%D1%80%D1%8D%D1%85%D0%B5%D0%BC,_%D0%AD%D0%BD%D0%B4%D1%80%D1%8E,_%D0%A7%D0%B5%D0%BD,_QuickHull#.D0.90.D0.BB.D0.B3.D0.BE.D1.80.D0.B8.D1.82.D0.BC_.D0.94.D0.B6.D0.B0.D1.80.D0.B2.D0.B8.D1.81.D0.B0[еще одно описание]

=== Алгоритм Эндрю (верхние и нижние огибающие)

Идея в том, чтобы строить не сами оболочки, а их огибающие (правые и левые или верхние и нижние половины) и сливать их вместе. Огибающие строятся алгоритмом Грэхема.
Асимптотика \$O(n \log n)\$, но этот алгоритм работает в целом быстрее, чем обычный алгоритм Грэхема.

https://neerc.ifmo.ru/wiki/index.php?title=%D0%A1%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B2%D1%8B%D0%BF%D1%83%D0%BA%D0%BB%D1%8B%D0%B5_%D0%BE%D0%B1%D0%BE%D0%BB%D0%BE%D1%87%D0%BA%D0%B8:_%D0%94%D0%B6%D0%B0%D1%80%D0%B2%D0%B8%D1%81,_%D0%93%D1%80%D1%8D%D1%85%D0%B5%D0%BC,_%D0%AD%D0%BD%D0%B4%D1%80%D1%8E,_%D0%A7%D0%B5%D0%BD,_QuickHull#.D0.90.D0.BB.D0.B3.D0.BE.D1.80.D0.B8.D1.82.D0.BC_.D0.AD.D0.BD.D0.B4.D1.80.D1.8E[подробное описание]

https://ru.algorithmica.org/cs/convex-hulls/envelope/[еще одно описание]

=== Алгоритм Чана

В случае небольших оболочек алгоритм Джарвиса работает лучше алгоритма Грэхема, а в случае больших - наоборот. Алгоритм Чана пытается объединить эти алгоритмы, чтобы получить асимптотику \$O(n log h)\$.
Идея в том, чтобы разбить точки на группы, в каждой из групп найти выпуклую оболочку алгоритмом Грэхема, а потом найти общую выпуклую оболочку алгоритмом Джарвиса. На практике этот алгоритм слабо применим.

https://ru.algorithmica.org/cs/convex-hulls/chan/[описание]

== Алгоритмы триангуляции

Триангуляция - это декомпозиция многоугольника на треугольники.

=== Примитивный алгоритм
*TODO*

=== Монотонный метод
*TODO*

=== Ушной метод
*TODO*

== Задачи регионального поиска и локализации
*TODO*

== Алгоритмы планирования движения
*TODO*