= Разрешимость

Понятие алгоритма. Разрешимые и перечислимые языки. Алгоритмически неразрешимые задачи. Проблема останова. Теорема Райса.

== Понятие алгоритма

Определение алгоритма это то же самое, что модель вычислений 

* машина тьюринга, 
* лямбда-исчислений,
* частично-рекурсивные функции,
* RAM-машина (нужна бесконечная битность, чтобы адресовывать)

Вычисление -- это переписывание (преобразование), и алгоритм задает его правила 

Машина Тьюринга -- лента с курсором. На летнте записаны символы из алфавита E. Есть некоторое конечное множество состояний Q (стартоврое q0, q_end) и таблица переходов.

Программа для машины тьюринга 

p: Q x E -> Q (новое состояние) x E (что записать на ленту) x {_, <-, ->} (что делать с указатлем, перемещать ли его)

Алгоритм для недетерминированной машины Тьюринга:

p: Q x E x Q x E x {_, <-, ->} 


Машина Тьюринга с бесконечное лентой хотя бы в 1 сторону.

 Машина с ограниченной лентой -- конечный автомат?


=== Общие свойства всех алгоритмов 

у ДН

==== Разрешимо ли множество 
{n | содержится ли в числе pi n семерок подряд}

Да. Либо все есть. Либо существует n', больше которого нет.


== Теорма поста 
Если X размершимо <=> X, X' перечислимы


1. #Алгоритмом# для решения задачи P будем называть программу, записанную на алгоритмическом языке, которая получает на вход условие задачи P и вычисляет ответ для это задачи. Мы будем говорить, что алгоритм *корректен*, если для любого условия задачи P алгоритм находит верное решение.

2. #Алгоритм# -- конечная совокупность точно заданных правил решения произвольного класса задач или набор инструкций, описывающих порядок действий исполнителя для решения некоторой задачи.

== Разрешимое множество 

Алгоритмы перечислимы

функция из натуральных в булеан -- по мощности как множестве всех подмножеств, а оно несчетно 

=== Универсальная функция 
Универсальная функция: функция из пары чисел в другое число, где первое число задает программу, а второе -- вход 

U(n, x) = y

И удовлетворяет следующими свойствами

* если  f вычислимая функция => существует n: U_n = f
* любая вычислимая имеет номер, любой номер задает вычислимую функцию (у одной функции мб сколько угодно номеров)

W = {s| s(s) останавливается}

==== не перечислимое
это наш W!

== Проблема остановки
(туда как подмножество входит самоприменение, а оно неразрешимо)

== Теорема Успенского-Райса
аааааааааааааааа



== Бесконечное множество
У бесконечного множества есть собсветнное подмножество -- не пустое и не совпадает с ним, но такой же мощности (это как когда мы целым чисам неченые)

отображение -- частный случай отношение (один элемент в 1 элемент)

функция -- частный случай отношения

отношение -- подмножество декартова произведения

отношение эквивалентности

* транзитивно
* симметрично
* рефлексивно

Эквивалентность задает разбиение множества на непересекающиеся множества

фактор-множество (X/~) -- множество всех классов эквивалентности в этом разбиении

  почему фактор? фактризация -- это разбиение 

Линейный порядок -- для любых двух элементов либо они болбше, либо меньше, либо равны

