= Неразрешимость
:stem:

 Алгоритмически неразрешимые задачи. Проблема останова. Теорема Райса.

Неразрешимые множества существуют просто потому, что алгоритмов (и поэтому разрешимых подмножеств натурального ряда) счётное число, а всех подмножеств натурального ряда несчётное число

 TODO Почему алгоритмов счетное число?

Есть 3 свойства записи алгоритма, которые невозможно выполнить *одновременно*:

1. stem:[q_i(j)] не зависает для любых i, j

 Не верно для обычных языков

2. С помощью q можно задать любое разрешимое (никогда не зависает!) множество А: stem:[\forall A = {j | q_i(j) = 1}] для некоторого i.

 на конечных автоматах можно задать только регулярные языки 

3. По номеру входа и коду хотим получать результата работы (i, j) stem:[\to q_i(j)] -- вычислимая функция 

 Не выполнено: 

== Алгоритмически неразрешимые задачи

В теории вычислимости #алгоритмически неразрешимой задачей# называется задача, которая 

1. имеет ответ да или нет для каждого объекта из некоторого множества входных данных
2. (принципиально) не имеет алгоритма, который бы на любом входе, давал правильный ответ за конечное число шагов. 


* Универсальный язык неразрешим  (лекция 1:01:00)
* Комбинаторные неразрешимые задачи: проблема соответствий Поста, задача о замощении

== Проблема останова footnote:[https://www.youtube.com/watch?v=ffpHXORbRRY&list=PL4_hYwCyhAvbxuVVn5QJqr1FITycr93SN&index=10]

"Проблема остановки" - это проблема поиска универсального алгоритма, позволяющего по записи произвольного алгоритма (например, функциональной таблицы машины Тьюринга), а также по записи произвольного "входа" - установить, остановится ли вычислительное устройство, действующее в соответствие с данным алгоритмом и обрабатывающее данный "вход", или же оно будет работать бесконечно долго.

=== Подробности

*Универсальная вычислимая функция* U: N x N -> N -- функция двух аргументов:

* Вычислима как функция двух аргументов 
* В ней заключены все вычислимые функции одного аргумента

stem:[\forall f: N \to N ] (вычислимой) stem:[\exists p \forall x U(p, x) = f(x)]

 U -- компилятор языка, который получает код программы, её вход и возвращает ответ. 
 
 Программа с синтаксической ошибкой -- нигде не определена. 
 
 Такой язык универсальный (Тьюринг полный -- для любой машины тьюринга одного аргумента есть программа на этом языке, которая вычислит функцию).

Рассмотрим диагональное множество stem:[S = {n | U(n, n)}] -- множество самоприменимых программ. Его дополнение не пустое (есть программы, нигде не определенные). И само множество не пустое -- есть всюду определенные (константы, например).

Теорема: множество S перечислимо, но не разрешимо.

Доказательство:

==== Перечислимо

S -- область определение диагональной функции d(n) = U(n, n). Диагональная функция вычислима => S перечислима (TODO существует теорема об этом).

 TODO Почему диагональная функция вычислима?

==== Неразрешимость (диагональный метод): 

Предположим, что S разрешимо. Тогда можно использовать алгоритм, который проверяет принадлежность к S и вычислима функция: 

stem:[d'(n) = ((1 if (U(n, n) - no~def)),(no~def if (U(n, n) - def)))]

stem:[= 1 if U(n, n) ]'не опр' и  'не опр', если stem:[U(n, n)] 'опр'.

Тогда из универсальности её можно найти в U: stem:[\exists p \forall n U(p, n) = d'(n)]

== Теорема Успенского-Райса footnote:[А. Шень, Вычислимые функции: https://old.mccme.ru/free-books/]

Теорема 21. Пусть A ⊂ F — произвольное нетривиальное свой-
ство вычислимых функций (нетривиальность означает, что есть как
функции, ему удовлетворяющие, так и функции, ему не удовлетво-
ряющие, то есть что множество A непусто и не совпадает со всем F).

Пусть U — главная универсальная функция. Тогда не существует ал-
горитма, который по U-номеру вычислимой функции проверял бы,
обладает ли она свойством A. Другими словами, множество stem:[{ n| U_n ∈
∈ A}] неразрешимо.

https://www.youtube.com/watch?v=nVqEdUNrXLE
//TODO доказательство (есть у Шеня)
