= Неразрешимость

Неразрешимые множества существуют просто потому, что алгоритмов (и поэтому разрешимых подмножеств натурального ряда) счётное число, а всех подмножеств натурального ряда несчётное число

Есть 3 свойства записи алгоритма, которые невозможно выполнить *одновременно*:

1. stem:[q_i(j)] не зависает для любых i, j

 Не верно для обычных языков

2. С помощью q можно задать любое разрешимое (никогда не зависает!) множество А: stem:[\forall] А 
stem:[A = {j | q_i(j) = 1}] для некоторого i.

 на конечных автоматах можно задать только регулярные языки 

3. По номеру входа и коду хотим получать результата работы (i, j) stem:[\to q_i(j)] -- вычислимая функция 

 Не выполнено: 

== Алгоритмически неразрешимые задачи

В теории вычислимости #алгоритмически неразрешимой задачей# называется задача, имеющая ответ да или нет для каждого объекта из некоторого множества входных данных, для которой (принципиально) не существует алгоритма, который бы, получив любой возможный в качестве входных данных объект, останавливался и давал правильный ответ после конечного числа шагов. 


* Универсальный язык неразрешим  (лекция 1:01:00)
* Комбинаторные неразрешимые задачи: проблема соответствий Поста, задача о замощении

== Проблема останова. Теорема Райса.
