:stem:

= Разрешимые и перечислимые языки


https://www.youtube.com/watch?v=2duqp1Kt160&list=PLHX_ZgKaM8sJD1d2SrFikhhmwDqiqsrqy&index=9[Лекция Станкевича: ИТМО ДМ]

http://neerc.ifmo.ru/wiki/index.php?title=%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8#.D0.A0.D0.B0.D0.B7.D1.80.D0.B5.D1.88.D0.B8.D0.BC.D1.8B.D0.B5_.D0.B8_.D0.BF.D0.B5.D1.80.D0.B5.D1.87.D0.B8.D1.81.D0.BB.D0.B8.D0.BC.D1.8B.D0.B5_.D1.8F.D0.B7.D1.8B.D0.BA.D0.B8[NEERC ITMO: Теория вычислимости]

https://old.mccme.ru//free-books//shen/shen-logic-part3-2.pdf[Н. К. Верещагин, А. Шень. Лекции по математической логике и теории алгоритмов. Часть 3. Вычислимые функции. — М.: МЦНМО, 1999, с. 16. ISBN 5-900916-36-7 ]

== Разрешимость

stem:[\Sigma] -- конечный алфавит

stem:[\Sigma^* = \cup_{k=0}^ \infty \Sigma^k] -- множество всех слов над алфавитом. Слова конечной длинны, но их бесконечно много.

stem:[L \subset \Sigma^*]  -- формальный  язык (подмножество слов)

Язык L -- #разрешимый (рекурсивный)#, если существует #характеристическая функция# -- программа p, которая для слов языка выдает 1, а для слов, не входящих в язык, 0.

stem:[\exists p : x \in L \to p(x) = 1, x \notin L \to p(x) = 0] 


 Почему рекурсивный? В теории функций базовая функция -- прибавление единицы, более сложные -- рекурсивные. Затем было обнаружено, что они разрешимы.


=== Замечание 
Множество разрешимых языков счётно.

=== Замечание 
Любой конечный язык разрешим (можно просто перечислить ответ для каждого слова).

```
p(x):
    if x == x1:
        return 1
    if x == x2:
        return 1
    ...
    return 0
```

Почти все языки несчетны stem:[2^{\Sigma^*}] (док-во: диагональным методом)


== Изоморфизм 

1. stem:[\Sigma^*] -- множество всех слов языка.

2. stem:[\N^+] -- множество натуральных чисел, расширенное нулём.

3. stem:[Prog] -- множество всех программ (всех слов принадлежащих языку программирования L)

Все эти три множества естественно изоморфны, а потому их можно отожествлять (число, слово и программа -- эквивалентны)

1-3 изменим компилятор: если программа не компилируется, то все равно скомпилируем её, но результатом будет программа, которая на любом входе *зависает*. Теперь любая строка над алфавитом -- корректная (но зависающая) программа. Теперь программы и строки -- это одно и то же, и программы можно передавать на вход другим программам.

1-2 упорядочим строки в градуированном лексикографическом порядке (grlex): по возрастанию длинны, а при равной длине -- лексикографически (eps, 0, 1, 00, 01... -- есть биекция в натуральные числа).  

 Обычный лексикографический не подойдет, т.к. тогда сперва будут все строки из младшего символа. Это не изоморфмно порядку на натуральных числах (eps, 0, 00, 000, ...).

== Перечислимость (полуразрешимость)

L -- #полуразрешимый# (перечислимый, рекурсивно перечислимый) если существует программа,которая на слове языка возвращает 1, а для остальных -- не возвращает единицу (может, не завершается вовсе).

=== Замечание 
Множество перечислимых языков счетно

=== Утверждение
Любой разрешимый язык является полуразрешимым

L -- перечислимый, если существует #перечислитель#: такая программа p, которая на пустом входе выводит все слова языка L хотя бы один раз. Слова не из языка не будут выведены.

Если язык бесконечный, то для любого слова существует время, за которое перечислитель выведет его.

L -- полуразрешимый stem:[\iff] L -- перечислимый

==== Доказательство
Перечислим stem:[\to] полуразрешим

С помощью перечислителя (listL) можно реализовать программу, которая выводит 1, если число принадлежит языку и 0 (или в бесконечном цикле) в другом случае stem:[\to] полуразрешимо

```[python]
inL(x):
    progs = listL()
    if x in progs:
        return 1
    while true:
        pass
```


Полуразрешим stem:[\to] перечислим 

```
listL():
    for(t = 0; true; t++):
        # нельзя писать два вложенных бесконечных цикла
        # иначе первый бесконечный никогда не закончится
        for(x in Sigma^*[0,...t-1]):
            if inL(x, timeLimit = t):
                print(x)
```

Эта программа выведет все слова из языка и только их. Если x слово в языке, то за конечное время t' полу-разрешитель выведет его. Тогда и перечислитель напечатает его на итерации max(t', stem:[x \to \N]). 