= indirect questions

Для таких вопросов характерен прямой порядок слов, то есть сказуемое в них следует за подлежащим, как в утвердительных предложениях. footnote:[https://foxford.ru/wiki/angliyskiy-yazyk/pryamye-i-kosvennye-voprosy-direct-and-indirect-questions?utm_referrer=https%3A%2F%2Fwww.google.com%2F]

в косвенных вопросах НЕ используются did, do, does

*{вводная фраза} {вопросительное слово} {подлежащее} {сказуемое}?*

What *is he* doing? -> Could you tell me what *he is* doing?

I wonder when *he returned*.

Could you tell me where I *can stay*?

== Косвенный общий вопрос 
Заменяет *did/does/do*

*{вводная фраза} {if/whether} {подлежащее} {сказуемое}?*

Could you tell me if/whether I *can stay*?

I wonder if/whether *he returned*.

Did he admit his mistake? -> Can you tell me whether he admit his mistake?


== Two questions

Do you know .....

Can you tell me .....

Ты знаешь, где он живет?

Do you know where he lives?

Ты помнишь, что он сказал вчера?

Do you remember what he said yesterday.

* Can / could you tell me…, 
* Do you know…, 
* I’d like to know…, 
* Do you mind…, 
* I was wondering…,
* I'd like to know ...
* Could you tell me...
* * where he lives?
* * where the nearest supermarket is?

Is admission to the British Museum free of charge? — Do you know, if admission to the British Museum is free of charge?

== One question 

Ты знаешь, любит ли он кофе?

Do you know IF/WHETHER  he likes coffee?

WHETHER можно перевести как "ли"

Ты знаешь, что он любит?

Ты знаешь, какой кофе он любит?

Ты знаешь, любит ли он кофе?
