= Wish / only

* Предложения с wish переводятся на русский язык следующими фразами: «Жаль, что… не…», «Как жаль, что… не…», «Как бы мне хотелось, чтобы…», «Хорошо бы, если бы…»

== Сожаление о настоящем
* Чтобы выразить сожаление о том, что ситуация в *настоящем* складывается не так, как хотелось бы.

* I wish + Past Simple (V2, ed)

* !Глагол “to be” в данном случае проявляет особый характер: по правилам, в прошедшем времени мы сказали бы «he/she/it was”, но после “I wish” мы используем только форму “were” со всеми местоимениями.


=== Примеры  

* I wish I knew the answer!
* I wish you were here!

* I wish there were fewer homeless people in the world.
Как бы я хотела, чтобы в мире было меньше бездомных.

* He wishes I didn’t walk late in the evening.
Как бы ему хотелось, чтобы я не гулял поздно вечером.

* We wish it wasn’t drizzling.
Жаль, что моросит дождь.

* I wish you weren’t laughing at me.
Жаль, что ты смеёшься надо мной.

* I wish he wasn’t / weren’t speaking so quickly.
Как бы я хотел, чтобы он не говорил так быстро. 

=== ?
Past Continuous: was/were Ving

== Сожаление о прошлом
* I wish+ Past Perfect (had + V3.ed)

I wish we hadn’t done so much harm to nature.
Как жаль, что мы причинили столько вреда нашей планете.

I wish I had come to that concert.
Как жаль, что я не побывал на том концерте.

I wish she had been better-prepared for that exam.
Как бы я хотела, чтобы она лучше подготовилась к тому экзамену. 

=== Очень эмоциональное сожаление (нытьё?)

* Чтобы пожаловаться на кого-то или на что-то, показать недовольство ситуацией, которая не зависит от нас, и пожелать, чтобы она изменилась в будущем

* I wish + would + V
* Не говорим I wish I would (потому что наши действия зависят от нас)

 wish you wouldn’t disturb me!
Когда же вы прекратите меня беспокоить!

I wish you wouldn’t listen to loud music all day long.
Когда же вы перестанете громко слушать музыку весь день.


Конструкция if only …
Наряду с конструкцией I wish… можно использовать синонимичную конструкцию if only…, которая переводится на русский как «если бы», «если бы только».

If only I had come to that concert!
Если бы только я пришёл на тот концерт!

If only I was / were more gifted.
Если бы я был более талантливым.

== Упражнения 
https://wordwall.net/resource/28374499/i-wish-if-only

https://wordwall.net/resource/20678160/i-wish

https://wordwall.net/resource/27684064/english/conditionals-wish-if-only

https://www.liveworksheets.com/w/en/english-language/1995675

https://www.liveworksheets.com/w/en/english-second-language-esl/373836



