= 1. Процессоры общего назначениях. Архитектуры CISC и RISC. Конвейер. Суперскалярность. Кэширование команд и данных.

== Процессоры общего назначения footnote:[https://www.reg.ru/blog/chto-takoe-protsessor-cpu/]

Микропроцессоры общего назначения ориентированы на решение широкого круга задач цифровой обработки информации. Их основной областью применения являются персональные компьютеры, рабочие станции, серверы и другие системы массового применения.К этому классу относятся современные процессоры семейства Core компании Intel, Bulldozer компании AMD, PowerPC и Xenon компаний Motorola и IBM, SPARC компании Sun Microsystems и ряд других.




=== Функции CPU

* получает данные из оперативной памяти, выполняет с ними арифметические и логические операции, передаёт их на внешние устройства,

* формирует сигналы, необходимые для работы внутренних узлов и внешних устройств,
временно хранит результаты выполненных операций, переданных сигналов и других данных,

* принимает запросы от внешних устройств и обрабатывает их (?разве не драйвер?)


===  Структура

Центральный процессор состоит из 3-х частей:

* Ядро процессора, которое выполняет основную работу. Оно позволяет читать, расшифровывать, выполнять и отправлять инструкции. Ядро состоит из следующих частей:

** Арифметико-логическое устройство (АЛУ). Выполняет основные математические и логические операции. Все вычисления производятся в двоичной системе.

** Устройство управления (УУ). Управляет работой CPU с помощью электрических сигналов. От него зависит согласованность работы всех частей процессора и его связь с внешними устройствами.


* Запоминающее устройство. Это небольшая внутренняя память центрального процессора. Она состоит из регистров и кеш-памяти. В регистрах хранятся текущие команды, данные, промежуточные результаты операции. В кеш-память загружаются часто используемые команды и данные из оперативной памяти. 

* Шины ― это каналы, по которым передаётся информация

== Архитектуры CISC и RISC 

