= 1. Процессоры общего назначениях. Архитектуры CISC и RISC. Конвейер. Суперскалярность. Кэширование команд и данных.

== Процессоры общего назначения footnote:[https://www.reg.ru/blog/chto-takoe-protsessor-cpu/]footnote:[https://intuit.ru/studies/courses/13849/1246/lecture/32768]

Микропроцессоры общего назначения ориентированы на решение широкого круга задач цифровой обработки информации. Их основной областью применения являются персональные компьютеры, рабочие станции, серверы и другие системы массового применения.К этому классу относятся современные процессоры семейства Core компании Intel, Bulldozer компании AMD, PowerPC и Xenon компаний Motorola и IBM, SPARC компании Sun Microsystems и ряд других.


Центральный процессор
Центральный процéссоp (ЦП; англ. central processing unit, CPU, дословно - центральное вычислительное устройство) - исполнитель машинных инструкций, часть аппаратного обеспечения компьютера или программируемого логического контроллера, отвечающий за выполнение операций, заданных программами.

Основные характеристики
1. Тактовая частота.
2. Частота обмена с системной шиной.
3. Объём кэш-памяти.
4. Количество ядер.
5. Тип сокета.
В состав центрального процессора входят:
устройство управления (УУ);
арифметико-логическое устройство (АЛУ);
запоминающее устройство (ЗУ) на основе регистров процессорной памяти и кэш-памяти процессора;
генератор тактовой частоты (ГТЧ).

=== Функции CPU

* получает данные из оперативной памяти, выполняет с ними арифметические и логические операции, передаёт их на внешние устройства,

* формирует сигналы, необходимые для работы внутренних узлов и внешних устройств,
временно хранит результаты выполненных операций, переданных сигналов и других данных,

* принимает запросы от внешних устройств и обрабатывает их (?разве не драйвер?)


===  Структура

Центральный процессор состоит из 3-х частей:

* Ядро процессора, которое выполняет основную работу. Оно позволяет читать, расшифровывать, выполнять и отправлять инструкции. Ядро состоит из следующих частей:

** Арифметико-логическое устройство (АЛУ). Выполняет основные математические и логические операции. Все вычисления производятся в двоичной системе.

** Устройство управления (УУ). Управляет работой CPU с помощью электрических сигналов. От него зависит согласованность работы всех частей процессора и его связь с внешними устройствами.


* Запоминающее устройство. Это небольшая внутренняя память центрального процессора. Она состоит из регистров и кеш-памяти. В регистрах хранятся текущие команды, данные, промежуточные результаты операции. В кеш-память загружаются часто используемые команды и данные из оперативной памяти. 

* Шины ― это каналы, по которым передаётся информация

 
=== производительность

Она зависит от двух параметров: тактовая частота и разрядность.

Тактовая частота ― число выполненных операций в секунду. Измеряется в мегагерцах (МГц — миллион тактов в секунду ) и гигагерцах (ГГц — миллиард тактов в секунду). Чем больше тактовая частота, тем быстрее работает машина.

Разрядность ― количество информации (байт), которое можно передать за такт. Разрядность процессора бывает 8, 16, 32, 64 бита. Современные процессоры 32-х и 64-битные.

== Архитектуры CISC и RISC 

== CISC footnote:[https://intuit.ru/studies/courses/13849/1246/lecture/32769]
CISC (Complicated Instruction Set Computer)

менфреймы IBM System/360, intel x86

=== Свойства 

* Выразительность системы команд (сложные команды из нескольких действий, операции с массивами и т.д.)
* Гибкость при задании аргументов команд 
* Экономное (в среднем) кодирование (популярные команды кодируются меньшим числом байт) 
* Существенно разная длительность выполнения команд

=== Недостатки
[minuses]
* сложно разрабатывать, высокий риск ошибки 
* высокая стоимость 
* сложная система команд затрудняет внутрипроцессорные оптимизации, например, автоматическое распараллеливание выполнения машинных команд.
