= 1. Процессоры общего назначениях. Архитектуры CISC и RISC. Конвейер. Суперскалярность. Кэширование команд и данных.

== Процессоры общего назначения footnote:[https://www.reg.ru/blog/chto-takoe-protsessor-cpu/]footnote:[https://intuit.ru/studies/courses/13849/1246/lecture/32768]

Микропроцессоры общего назначения ориентированы на решение широкого круга задач цифровой обработки информации. Их основной областью применения являются персональные компьютеры, рабочие станции, серверы и другие системы массового применения.К этому классу относятся современные процессоры семейства Core компании Intel, Bulldozer компании AMD, PowerPC и Xenon компаний Motorola и IBM, SPARC компании Sun Microsystems и ряд других.


Центральный процессор
Центральный процéссоp (ЦП; англ. central processing unit, CPU, дословно - центральное вычислительное устройство) - исполнитель машинных инструкций, часть аппаратного обеспечения компьютера или программируемого логического контроллера, отвечающий за выполнение операций, заданных программами.

Основные характеристики
1. Тактовая частота.
2. Частота обмена с системной шиной.
3. Объём кэш-памяти.
4. Количество ядер.
5. Тип сокета.
В состав центрального процессора входят:
устройство управления (УУ);
арифметико-логическое устройство (АЛУ);
запоминающее устройство (ЗУ) на основе регистров процессорной памяти и кэш-памяти процессора;
генератор тактовой частоты (ГТЧ).

=== Функции CPU

* получает данные из оперативной памяти, выполняет с ними арифметические и логические операции, передаёт их на внешние устройства,

* формирует сигналы, необходимые для работы внутренних узлов и внешних устройств,
временно хранит результаты выполненных операций, переданных сигналов и других данных,

* принимает запросы от внешних устройств и обрабатывает их (?разве не драйвер?)


===  Структура

Центральный процессор состоит из 3-х частей:

* Ядро процессора, которое выполняет основную работу. Оно позволяет читать, расшифровывать, выполнять и отправлять инструкции. Ядро состоит из следующих частей:

** Арифметико-логическое устройство (АЛУ). Выполняет основные математические и логические операции. Все вычисления производятся в двоичной системе.

** Устройство управления (УУ). Управляет работой CPU с помощью электрических сигналов. От него зависит согласованность работы всех частей процессора и его связь с внешними устройствами.


* Запоминающее устройство. Это небольшая внутренняя память центрального процессора. Она состоит из регистров и кеш-памяти. В регистрах хранятся текущие команды, данные, промежуточные результаты операции. В кеш-память загружаются часто используемые команды и данные из оперативной памяти. 

* Шины ― это каналы, по которым передаётся информация

 
=== производительность

Она зависит от двух параметров: тактовая частота и разрядность.

Тактовая частота ― число выполненных операций в секунду. Измеряется в мегагерцах (МГц — миллион тактов в секунду ) и гигагерцах (ГГц — миллиард тактов в секунду). Чем больше тактовая частота, тем быстрее работает машина.

Разрядность ― количество информации (байт), которое можно передать за такт. Разрядность процессора бывает 8, 16, 32, 64 бита. Современные процессоры 32-х и 64-битные.

== Архитектуры CISC и RISC 

== CISC footnote:[https://intuit.ru/studies/courses/13849/1246/lecture/32769]
CISC (Complicated Instruction Set Computer)

менфреймы IBM System/360, intel x86

=== Свойства 

* Выразительность системы команд (сложные команды из нескольких действий, операции с массивами и т.д.)
* Гибкость при задании аргументов команд 
* Экономное (в среднем) кодирование (популярные команды кодируются меньшим числом байт) 
* Существенно разная длительность выполнения команд

=== Недостатки
[minuses]
* сложно разрабатывать, высокий риск ошибки 
* высокая стоимость 
* сложная система команд затрудняет внутрипроцессорные оптимизации, например, автоматическое распараллеливание выполнения машинных команд.

 Многие CISC-процессоры реализуют сложные команды с помощью микрокода - специализированного машинного языка, позволяющего задавать последовательность действий (микроопераций), выполняемую одной машинной командой процессора. Таким образом команды CISC-процессоров оказываются настолько сложными, что их приходится описывать при помощи дополнительного машинного языка, который исполняется специализированным процессором внутри процессора.
 

== RISC 
небольшая система команд, каждая команда имеет эффективную аппаратную реализацию.

=== Особенности 
* Минималистичность системы команд. Машинные команды RISC-процессора имеют простую функциональность, соответственно, время на их декодирование и исполнения оказывается небольшим, а блоки процессора, отвечающие за декодирование - простыми
* Отсутствие гибкости в задании аргументов (операнды могут храниться только в регистрах, поэтому регистров общего назначения у таких процессоров дольше)
* Унифицированное кодирование. Двоичное представление разных машинных команд (то есть соответствующий им машинный код) имеет одинаковый формат и фиксированный размер. Для большинства RISC-архитектур одна команда занимает одно машинное слово. Таким образом имеется простой и "единообразный" машинный язык.
* Фиксированное время выполнения команд (количество тактов)

 имеется некоторое количество сложных команд, время исполнения которых может существенно превышать стандартное, например, умножение и деление. Эти операции сложнее, чем сложение и вычитание: они требуют выполнения большого количества сдвигов, сложений/вычитаний и различных проверок. Поскольку такие команды выбиваются из стройной концепции RISC, для их реализации применяют специальные приёмы. В частности, команда деления исполняется асинхронно - само деление далее выполняется отдельным специальным блоком процессора, в то время как сам процессор исполняет другие команды. При этом исполняемая программа "знает", через сколько тактов деление завершится, и также знает, где (в каких регистрах) будут расположены частное и остаток от деления.

=== преимущества
* Упрощение и удешевление процессоров, как при конструировании, так и при производстве.
* Обширные возможности для реализации различных оптимизаций, в частности, внутрипроцессорного распараллеливания.

=== недостатки 
* общий объем кода больше

== Конвейер. 
Конвейер - это механизм, предназначенный для распараллеливания выполнения команд программы между блоками процессора. Он позволяет загрузить блоки процессора при выполнении команд оптимально, без простоев.

Ситуации, возникающие при конвейеризованном исполнении команд, которые препятствуют корректному выполнению очередной команды, называются конфликтами.

Конфликты бывают следующих видов.

1. Конфликт по данным между зависимыми машинными командами заключается в том, что на конвейере одновременно находятся на разных стадиях выполнения команды, которые могут быть корректно исполнены лишь строго последовательно.

2. Конфликт по ресурсам возникает в ситуации, когда двум командам на конвейере одновременно нужен доступ к какому-либо блоку процессора, с которым в один момент времени может работать только одна команда.

3. Конфликт по управлению заключается в том, что следующая команда на конвейере является условным переходом, но условие для него ещё не вычислено предыдущей командой и не понятно, какую ветку условного оператора следует загружать на конвейер.


Выделим следующие подходы к обработке конфликтов.

1. Статическое переупорядочивание машинных команд при компиляции программ с языков высокого уровня в машинный код.

2. "Разнесение" конфликтующих команд при компиляции на безопасное расстояние друг от друга с помощью вставки необходимого количества специальной команды NOP (No Operation). Команда NOP ничего не делает, но замедляет работу программы на один такт, в некоторых процессорах - и на большее число тактов.

3. Динамическая обработка конфликтов во время исполнения программы - идентификация и разрешение конфликтов выполняется в момент выполнения программы. При этом процессор задерживает выполнение зависимых команд (как, например, Intel 80486), а также самостоятельно переупорядочивает команды, чтобы исключить конфликты с минимизацией потери времени (так действуют процессор Intel Pentium и последующие процессоры семейств Intel x86).

== Суперскалярность. 

Суперскалярность - возможность одновременно выполнять несколько машинных команд за счёт наличия в процессоре нескольких однотипных функциональных блоков (арифметико-логических устройств, математических сопроцессоров и т.д.) 

 В семействе Intel x86 первым процессором, где была реализована суперскалярность, был процессор Intel Pentium (1993 год). Этот процессор содержал два арифметико-логических устройства, которые позволяли исполнять одновременно две соседние команды, если они не зависели друг от друга. При этом независимые команды одновременно обрабатывались двумя разными конвейерами. Для этого компиляторы стремились генерировать машинный код, соседние команды которого не зависели бы друг от друга.

== Кэширование команд и данных footnote:[Таненбаум, архитектура]

должны ли команды и данные находиться вместе в общей кэш-памяти? Проще разработать смежную кэш-память, в которой хранятся и дан-ные, и команды. При этом вызов команд и данных автоматически уравновешива-ется. Тем не менее в настоящее время существует тенденция к использованию разделенной кэш-памяти, когда команды хранятся в одной кэш-памяти, а данные — в другой. Такая структура также называется Гарвардской (Harvard Architecture), поскольку идея использования отдельной памяти для команд и отдельной памяти для данных впервые воплотилась в компьютере Маге III, который был создай Го-вардом Айкеном в Гарварде.

Современные разработчики пошли по этому пути, поскольку сейчас широко используются процессоры с конвейерами, а при такой организации должна быть возможность одновременного доступа и к командам, и к данным (операндам). Разделенная кэш-память позволяет осуществлять параллель-ный доступ, а общая — нет. К тому же, поскольку команды обычно не меняются во время выполнения, содержание командной кэш-памяти никогда не приходится записывать обратно в основную память.
