2. Оперативная память. 

Способы адресации. Реальный и защищенный режим работы процессора. Виртуальная память. Страничная организация памяти. Файлы подкачки, алгоритмы выгрузки страниц.

== Оперативная память footnote:[https://ru.m.wikipedia.org/wiki/Оперативная_память#:~:text=Операти́вная%20па́мять%20(англ.%20Random%20Access,устройство%2C%20реализующее%20функции%20оперативной%20памяти]

Операти́вная па́мять (англ. Random Access Memory, RAM — память с произвольным доступом) — в большинстве случаев энергозависимая часть системы компьютерной памяти, в которой во время работы компьютера хранится выполняемый машинный код (программы), а также входные, выходные и промежуточные данные, обрабатываемые процессором. Оперативное запоминающее устройство (ОЗУ) — техническое устройство, реализующее функции оперативной памяти. 

== Способы адресации footnote:[https://intuit.ru/studies/courses/56/56/lecture/1664?page=2] footnote:[Таненбаум, архитектура]
Используются для работы с данными и указания мест перехода.

Основные способы адресации:

Прямая адресация. Физический адрес операнда совпадает с кодом в адресной части команды.

Непосредственная адресация. В команде содержится не адрес операнда, а непосредственно сам операнд.

Косвенная адресация. Адресная часть команды указывает адрес ячейки памяти или номер регистра, в которых содержится адрес операнда.

Относительная адресация. Этот способ используется, когда память логически разбивается на блоки, называемые сегментами. В этом случае адрес ячейки памяти содержит две составляющие: адрес начала сегмента (базовый адрес) и смещение адреса операнда в сегменте.

Индексная адресация Часто нужно уметь обращаться к словам памяти по известному смещению. Обращение к памяти по регистру и константе смещения

Относительная индексная адресация В некоторых машинах применяется способ адресации, при котором адрес вычис-ляется путем суммирования значений двух регистров и смещения (смещение фа-культативно). Такой подход называется относительной индексной адресацией. Один из регистров — это база, а другой — это индекс.

== Реальный и защищенный режим работы процессора footnote:[https://ru.m.wikipedia.org/wiki/Режим_работы_процессора]
Режим работы процессора (англ. CPU mode) — состояние процессора, определяющее его поведение при выполнении различных команд и возможность доступа к различным данным.

По способу адресации памяти (на примере x86):

* Реальный режим: обращение к оперативной памяти происходит по реальным (действительным) адресам. Набор доступных операций не ограничен, защита памяти не используется.

* Защищённый режим: обращение к памяти происходит по виртуальным адресам с использованием механизмов защиты памяти. Набор доступных операций определяется уровнем привилегий.

По уровню привилегий:

* Режим пользователя (прикладной): минимальный уровень привилегий, разрешены только операции с данными и переходы в пределах адресного пространства пользователя. Все остальные операции либо игнорируются, либо с помощью механизма обработки исключений вызывают переключение в привилегированный режим и передачу управления ядру операционной системы для выполнения специальных функций (например, отображения данных на дисплее) или аварийного завершения потока управления.

* Привилегированный режим (режим ядра): наравне с операциями режима пользователя, разрешены дополнительные операции — запрет или разрешение прерываний, доступ к портам ввода-вывода, специальным регистрам процессора (например, для настройки блока управления памятью).
После включения процессор всегда начинает работу в реальном привилегированном режиме.

Переключение с понижением уровня привилегий (из режима ядра в режим пользователя) возможно с продолжением работы в любой конфигурации и с любого адреса. Обратное переключение (с повышением уровня привилегий) возможно лишь в определенные конфигурации и адреса в коде, заранее установленные в привилегированном режиме, за счет чего обеспечивается полный контроль ядра за повышением привилегий исполняемого кода.

== Виртуальная память 

== Страничная организация памяти

== Файлы подкачки, алгоритмы выгрузки страниц
