2. Оперативная память. 

Способы адресации. Реальный и защищенный режим работы процессора. Виртуальная память. Страничная организация памяти. Файлы подкачки, алгоритмы выгрузки страниц.

== Оперативная память footnote:[https://ru.m.wikipedia.org/wiki/Оперативная_память#:~:text=Операти́вная%20па́мять%20(англ.%20Random%20Access,устройство%2C%20реализующее%20функции%20оперативной%20памяти]

Операти́вная па́мять (англ. Random Access Memory, RAM — память с произвольным доступом) — в большинстве случаев энергозависимая часть системы компьютерной памяти, в которой во время работы компьютера хранится выполняемый машинный код (программы), а также входные, выходные и промежуточные данные, обрабатываемые процессором. Оперативное запоминающее устройство (ОЗУ) — техническое устройство, реализующее функции оперативной памяти. 

== Способы адресации footnote:[https://intuit.ru/studies/courses/56/56/lecture/1664?page=2] footnote:[Таненбаум, архитектура]
Используются для работы с данными и указания мест перехода.

Основные способы адресации:

Прямая адресация. Физический адрес операнда совпадает с кодом в адресной части команды.

Непосредственная адресация. В команде содержится не адрес операнда, а непосредственно сам операнд.

Косвенная адресация. Адресная часть команды указывает адрес ячейки памяти или номер регистра, в которых содержится адрес операнда.

Относительная адресация. Этот способ используется, когда память логически разбивается на блоки, называемые сегментами. В этом случае адрес ячейки памяти содержит две составляющие: адрес начала сегмента (базовый адрес) и смещение адреса операнда в сегменте.

Индексная адресация Часто нужно уметь обращаться к словам памяти по известному смещению. Обращение к памяти по регистру и константе смещения

Относительная индексная адресация В некоторых машинах применяется способ адресации, при котором адрес вычис-ляется путем суммирования значений двух регистров и смещения (смещение фа-культативно). Такой подход называется относительной индексной адресацией. Один из регистров — это база, а другой — это индекс.

== Реальный и защищенный режим работы процессора

== Виртуальная память 

== Страничная организация памяти

== Файлы подкачки, алгоритмы выгрузки страниц
