2. Оперативная память. 

Способы адресации. Реальный и защищенный режим работы процессора. Виртуальная память. Страничная организация памяти. Файлы подкачки, алгоритмы выгрузки страниц.

== Оперативная память footnote:[https://ru.m.wikipedia.org/wiki/Оперативная_память#:~:text=Операти́вная%20па́мять%20(англ.%20Random%20Access,устройство%2C%20реализующее%20функции%20оперативной%20памяти]

Операти́вная па́мять (англ. Random Access Memory, RAM — память с произвольным доступом) — в большинстве случаев энергозависимая часть системы компьютерной памяти, в которой во время работы компьютера хранится выполняемый машинный код (программы), а также входные, выходные и промежуточные данные, обрабатываемые процессором. Оперативное запоминающее устройство (ОЗУ) — техническое устройство, реализующее функции оперативной памяти. 

== Способы адресации
???

== Реальный и защищенный режим работы процессора

== Виртуальная память 

== Страничная организация памяти

== Файлы подкачки, алгоритмы выгрузки страниц
