= 3. Кластеры 

Рассмотрим классификацию многопроцессорных и многомашинных систем на основе степени разделения вычислительных ресурсов системы.

В этом случае выделяют следующие 4 класса систем:

* многопроцессорные:
* кластеры;
* MPP-системы вычислений с массовым параллелизмом (massively parallel processor).

== Многомашинные комплексы footnote:[https://intuit.ru/studies/courses/604/460/lecture/10345] footnote:[https://www.icmm.ru/uchebnaya-deyatelnost/lektsii/495-mnogomashinnye-i-mnogoprotsessornye-vychislitelnye-kompleksy-opredelenie-tipy-svyazej-i-strukturnaya-organizatsiya-osobennosti-programmnogo-obespecheniya-primery-otechestvennykh-i-zarubezhnykh-vychislitelnykh-kompleksov]

Многомашинная вычислительная система (ММС) содержит несколько ЭВМ, каждая из которых имеет свою операционную систему и средства обмена информацией между машинами. 

== Многопроцессорные комплексы 

Многопроцессорная вычислительная система (МПС) содержит несколько процессоров, работающих с общей оперативной памятью и управляемых одной общей операционной системой. В МПС достигается более быстрый обмен информацией между процессорами, что обеспечивает более высокую производительность, реакцию на ситуации внутри системы и в ее внешней среде, а также более высокие надежность и живучесть

Можно выделить два подвида:
** SMP-системы с симметричной мультипроцессорной обработкой (symmeTRic multIProcessINg) все компоненты общие с другими процессорами.
** NUMA-системы, построенные по технологии неоднородного доступа к памяти (non-un IForm memory access) каждый процессор имеет свою ОП, но может получать доступ к данным других процессоров (если хватает привелегий).

== Вычислительные кластеры.

== Распределенные системы.
