= 7. Передача данных по сети

== Удаленный доступ к ресурсам сети. 

== Организация электронной почты 
Система e-mail состоит из двух подсистем: 

=== пользовательских агентов (user agents)

это программа, предоставляющая графический интерфейс (а иногда интерфейс, основанный на тексте или командах), через ко-торый пользователи взаимодействуют с системой электронной почты.

* позволяют пользова-телям читать и отправлять письма

=== Агенты передачи сообщений (message transfer agents)
неформально можно называть почтовыми серверами (mail servers)

Агенты передачи сообщений, как правило, являются системными процессами, которые работают в фоновом режиме на устройствах почтовых серверов и всегда должны быть доступны. 

Они автоматически перемещают почтовые сообщения в системе от отправителя к получателю с помощью протокола SMTP

* пересылают письма от отправителя к получателю; 

 Агенты передачи также применяют списки рассылки (mailing lists), чтобы доставлять идентичные копии сообщений всем получателям в списке. Среди других полезных функций можно назвать следующие: копия письма, скры-тая копия, высокий приоритет письма, секретная (то есть зашифрованная) почта, доставка сообщения альтернативному получателю (если основной временно недоступен), а также возможность предоставить доступ к почте своему секретарю.

=== Почтовые ящики

Соединение пользовательских агентов и агентов передачи сообщений обеспечивают почтовые ящики и стандартный формат почтовых сообщений. 

Почтовые ящики (mailboxes) хранят доставленную почту. Они обслужива-ются почтовыми серверами. Пользовательские агенты просто предоставляют людям возможность увидеть содержимое их почтовых ящиков. Для этого агент отправляет команды почтовым серверам и получает возможность управлять почтовыми ящиками (проверять содержимое, удалять сообщения и т. д.). 

При такой архитектуре один пользователь может использовать различные пользовательские агенты на разных устройствах, чтобы получить доступ к одному и тому же почтовому ящику.

=== smtp

В интернете для доставки электронной почты компьютер-источник уста-навливает TCP-соединение с портом 25 компьютера-получателя. 

Этот порт прослушивается почтовым сервером, который поддерживает простой протокол передачи электронной почты (Simple Mail Transfer Protocol, SMTP). Есть два способа передачи сообщений

У становив TCP-соединение с портом 25, передающий компьютер, выступающий в роли клиента, ждет запроса принимающего компьютера, рабо-тающего в режиме сервера. Сервер начинает диалог с того, что отсылает тексто-вую строку с его идентификатором и информацией о том, готов ли он к приему почты. Если нет, клиент разрывает соединение и повторяет попытку позднее.

Если сервер готов принимать почту, клиент сообщает, от кого она поступила и кому предназначается. Если такой получатель существует на этом направлении, сервер дает клиенту добро на пересылку сообщения. Тогда клиент отправляет его, а сервер подтверждает его получение. Контрольные суммы не проверяются, так как TCP обеспечивает надежный байтовый поток. Если у отправителя есть еще почта, она также отсылается. После передачи всей почты в обоих направлениях соединение разрывается.

=== недастатки smtp

* не предусматривает аутентификации. Это означает, что команда FROM в нашем примере может отобразить какой угодно адрес отправителя, что крайне удобно для рассылки спама
* сообщения в кодировке ASCII, но не бинарные данные.
* отсылает сообщение в незашифрованном виде

=== Extended SMTP, ESMTP
Клиенты, желающие применить ESMTP, на первом этапе высылают EHLO вместо HELO. Если этот вариант отвергается, сервер работает с обычным SMTP , а пользователь должен идти по стандартному пути. Если EHLO принимается, сервер сообщает, какие расширения он поддерживает. После этого клиент может использовать любое из них.

=== Окончательная доставка сообщения 
SMTP основан на механизме push. Для передачи сообщения ему необходимо со-единение с удаленным сервером. Поэтому smpt не может доставлять сообщения на клиент, который может быть не подключен к сети.

Поэтому на этапе окончательной доставки чаще всего используется протокол доступа к электронной почте (Internet Mail Access Protocol, IMAP )	

 Это улучшенная версия протокола почтового отделения версии 3 (Post Office Protocol, version 3, POP3)

=== Веб-почта 

Популярной альтернативой IMAP и SMTP в деле предоставления почтовых ус-луг стало использование веб-интерфейса для отправки и получения сообщений. 

Широко применяются такие системы веб-почты (Webmail), как Google Mail, Microsoft Hotmail и Yahoo! Mail. Веб-служба электронной почты — это пример программного обеспечения (в данном случае почтового агента пользователя), которое предоставляется как интернет-служба.

В такой системе провайдер принимает сообщения для пользователей при помощи SMTP через порт 25. В этой модели подача почты происходит при использовании обычных веб-протоколов с отправкой данных по URL.


== Организация телеконференций. 


== Протоколы передачи файлов FTP и HTTP 

=== http 
https://fcc.gov/ Этот URL-адрес включает в себя три элемента: протокол (https), DNS-имя хоста (fcc.gov) и имя пути (/), которое веб-сервер часто воспринимает как не-который индексный объект по умолчанию.

Когда пользователь выбирает гиперссылку, браузер выполняет ряд действий для загрузки той страницы, на которую она указывает. Рассмотрим последова-тельность действий при активации ссылки в нашем примере:

1. Браузер определяет URL-адрес (исходя из того, какой элемент страницы выбрал пользователь).
2. Браузер запрашивает у службы DNS IP-адрес сервера fcc.gov.
3. DNS выдает в качестве ответа адрес 23.1.55.196.
4. Браузер устанавливает TCP-соединение с этим IP-адресом; поскольку при этом применяется HTTPS, защищенная версия HTTP , TCP-соединение по умолчанию устанавливается с портом 443 (а не со стандартным портом 80 протокола HTTP , который сегодня используется все реже).
5. Браузер отправляет HTTPS-запрос на получение страницы //, которую веб-сервер обычно интерпретирует как некую индексную страницу (например, index.html, index.php и т. п., как указано в конфигурации веб-сервера хоста fcc.gov).
6. Сервер отправляет страницу как HTTPS-ответ, например, в виде файла /index.html, если таковой определен как индексный объект по умолчанию.
7. Если страница содержит URL-адреса, которые нужно отобразить, то браузер получает их таким же способом. В нашем случае эти URL-адреса содержат ряд встроенных изображений, также загружаемых с данного сервера, встро-енные объекты с сайта gstatic.com и скрипт с сайта google-analytics.com (а также с ряда других доменов, которые здесь не показаны).
8. Браузер отображает страницу /index.html в том виде, в каком она представ-лена на рисунке (прикреплю??)
9. Если в течение некоторого времени на те же серверы не поступает других запросов, TCP-соединения обрываются

=== ftp 
Протокол ftp применяется для доступа к FTP-файлам.

== язык разметки гипертекста HTML, 

== разработка WEB-страниц,

== WWW-серверы.
