= 7. Передача данных по сети

== Удаленный доступ к ресурсам сети. 

== Организация электронной почты 
Система e-mail состоит из двух подсистем: 

=== пользовательских агентов (user agents)

это программа, предоставляющая графический интерфейс (а иногда интерфейс, основанный на тексте или командах), через ко-торый пользователи взаимодействуют с системой электронной почты.

* позволяют пользова-телям читать и отправлять письма

=== Агенты передачи сообщений (message transfer agents)
неформально можно называть почтовыми серверами (mail servers)

Агенты передачи сообщений, как правило, являются системными процессами, которые работают в фоновом режиме на устройствах почтовых серверов и всегда должны быть доступны. 

Они автоматически перемещают почтовые сообщения в системе от отправителя к получателю с помощью протокола SMTP

* пересылают письма от отправителя к получателю; 

 Агенты передачи также применяют списки рассылки (mailing lists), чтобы доставлять идентичные копии сообщений всем получателям в списке. Среди других полезных функций можно назвать следующие: копия письма, скры-тая копия, высокий приоритет письма, секретная (то есть зашифрованная) почта, доставка сообщения альтернативному получателю (если основной временно недоступен), а также возможность предоставить доступ к почте своему секретарю.

=== Почтовые ящики

Соединение пользовательских агентов и агентов передачи сообщений обеспечивают почтовые ящики и стандартный формат почтовых сообщений. 

Почтовые ящики (mailboxes) хранят доставленную почту. Они обслужива-ются почтовыми серверами. Пользовательские агенты просто предоставляют людям возможность увидеть содержимое их почтовых ящиков. Для этого агент отправляет команды почтовым серверам и получает возможность управлять почтовыми ящиками (проверять содержимое, удалять сообщения и т. д.). 

При такой архитектуре один пользователь может использовать различные пользовательские агенты на разных устройствах, чтобы получить доступ к одному и тому же почтовому ящику.

=== smtp

В интернете для доставки электронной почты компьютер-источник (в роли клиента) уста-навливает TCP-соединение с портом 25 компьютера-получателя (в роли сервера). Этот порт прослушивается почтовым сервером, который поддерживает простой протокол передачи электронной почты (Simple Mail Transfer Protocol, SMTP).




== Организация телеконференций. 


== Протоколы передачи файлов FTP и HTTP, 

== язык разметки гипертекста HTML, 

== разработка WEB-страниц,

== WWW-серверы.
