= 7. Передача данных по сети

== Удаленный доступ к ресурсам сети. 

== Организация электронной почты 
Система e-mail состоит из двух подсистем: 

=== пользовательских агентов (user agents)

это программа, предоставляющая графический интерфейс (а иногда интерфейс, основанный на тексте или командах), через ко-торый пользователи взаимодействуют с системой электронной почты.

* позволяют пользова-телям читать и отправлять письма

=== Агенты передачи сообщений (message transfer agents)
неформально можно называть почтовыми серверами (mail servers)

Агенты передачи сообщений, как правило, являются системными процессами, которые работают в фоновом режиме на устройствах почтовых серверов и всегда должны быть доступны. 

Они автоматически перемещают почтовые сообщения в системе от отправителя к получателю с помощью протокола SMTP

* пересылают письма от отправителя к получателю; 

 Агенты передачи также применяют списки рассылки (mailing lists), чтобы доставлять идентичные копии сообщений всем получателям в списке. Среди других полезных функций можно назвать следующие: копия письма, скры-тая копия, высокий приоритет письма, секретная (то есть зашифрованная) почта, доставка сообщения альтернативному получателю (если основной временно недоступен), а также возможность предоставить доступ к почте своему секретарю.

=== Почтовые ящики

Соединение пользовательских агентов и агентов передачи сообщений обеспечивают почтовые ящики и стандартный формат почтовых сообщений. 

Почтовые ящики (mailboxes) хранят доставленную почту. Они обслужива-ются почтовыми серверами. Пользовательские агенты просто предоставляют людям возможность увидеть содержимое их почтовых ящиков. Для этого агент отправляет команды почтовым серверам и получает возможность управлять почтовыми ящиками (проверять содержимое, удалять сообщения и т. д.). 

При такой архитектуре один пользователь может использовать различные пользовательские агенты на разных устройствах, чтобы получить доступ к одному и тому же почтовому ящику.

=== smtp

В интернете для доставки электронной почты компьютер-источник уста-навливает TCP-соединение с портом 25 компьютера-получателя. 

Этот порт прослушивается почтовым сервером, который поддерживает простой протокол передачи электронной почты (Simple Mail Transfer Protocol, SMTP). Есть два способа передачи сообщений

У становив TCP-соединение с портом 25, передающий компьютер, выступающий в роли клиента, ждет запроса принимающего компьютера, рабо-тающего в режиме сервера. Сервер начинает диалог с того, что отсылает тексто-вую строку с его идентификатором и информацией о том, готов ли он к приему почты. Если нет, клиент разрывает соединение и повторяет попытку позднее.

Если сервер готов принимать почту, клиент сообщает, от кого она поступила и кому предназначается. Если такой получатель существует на этом направлении, сервер дает клиенту добро на пересылку сообщения. Тогда клиент отправляет его, а сервер подтверждает его получение. Контрольные суммы не проверяются, так как TCP обеспечивает надежный байтовый поток. Если у отправителя есть еще почта, она также отсылается. После передачи всей почты в обоих направлениях соединение разрывается.

=== недастатки smtp

* не предусматривает аутентификации. Это означает, что команда FROM в нашем примере может отобразить какой угодно адрес отправителя, что крайне удобно для рассылки спама
* сообщения в кодировке ASCII, но не бинарные данные.
* отсылает сообщение в незашифрованном виде

=== Extended SMTP, ESMTP
Клиенты, желающие применить ESMTP, на первом этапе высылают EHLO вместо HELO. Если этот вариант отвергается, сервер работает с обычным SMTP , а пользователь должен идти по стандартному пути. Если EHLO принимается, сервер сообщает, какие расширения он поддерживает. После этого клиент может использовать любое из них.

=== Окончательная доставка сообщения 
SMTP основан на механизме push. Для передачи сообщения ему необходимо со-единение с удаленным сервером. Поэтому smpt не может доставлять сообщения на клиент, который может быть не подключен к сети.

Поэтому на этапе окончательной доставки чаще всего используется протокол доступа к электронной почте (Internet Mail Access Protocol, IMAP )	

 Это улучшенная версия протокола почтового отделения версии 3 (Post Office Protocol, version 3, POP3)

=== Веб-почта 

Популярной альтернативой IMAP и SMTP в деле предоставления почтовых ус-луг стало использование веб-интерфейса для отправки и получения сообщений. 

Широко применяются такие системы веб-почты (Webmail), как Google Mail, Microsoft Hotmail и Yahoo! Mail. Веб-служба электронной почты — это пример программного обеспечения (в данном случае почтового агента пользователя), которое предоставляется как интернет-служба.

В такой системе провайдер принимает сообщения для пользователей при помощи SMTP через порт 25. В этой модели подача почты происходит при использовании обычных веб-протоколов с отправкой данных по URL.


== Организация телеконференций

IP-телефони́я — телефонная связь по протоколу IP. Под IP-телефонией подразумевается набор коммуникационных протоколов, технологий и методов, обеспечивающих традиционные для телефонии набор номера, дозвон и двустороннее голосовое общение, а также *видеообщение* по сети Интернет или любым другим IP-сетям. 

Сигнал по каналу связи передаётся в цифровом виде и, как правило, перед передачей преобразовывается (сжимается), чтобы удалить избыточность информации и снизить нагрузку на сеть передачи данных.

Голосовой чат позволяет разговаривать как с одним пользователем, так и устраивать конференц-связь.

Как пример, рассмотрим Skype. Благодаря используемым кодекам (алгоритмам сжатия данных) SILK, G.729 и т.д. и при достаточной скорости интернет-соединения (30—60 кбит/с) в большинстве случаев качество звука сопоставимо с качеством обычной телефонной связи, а при хороших условиях соединения — заметно выше.

При установке соединения между ПК аудиоданные шифровались при помощи AES-256, для передачи ключа которого, в свою очередь, использовался 1024-битный ключ RSA. Открытые ключи пользователей сертифицируются центральным сервером Skype при входе в систему с использованием сертификатов RSA[40].

При голосовом звонке и широкополосном подключении к Интернету расходуется примерно одинаковое количество входящего и исходящего трафика. 

== Протокол передачи файлов HTTP 

HTTP — простой запросно-ответный протокол. Его старые версии обычно за-пускаются поверх TCP, однако его самая последняя версия, HTTP/3, также нередко работает поверх UDP

=== HTTPS 
Https фактически использует HTTP поверх защищенного транспортного протокола защиты транспортного уровня (Transport Layer Security, TLS), а потому извлекает объекты из веб-страниц более безопасно. HTTPS при этом можно рассматривать просто как HTTP , транспортируемый с помощью TLS.

=== Методы, запросы к серверу

* GET чтение веб-страницы 
* HEAD чтение заголовка веб-страницы 
* POST добавить к веб-странице 
* PUT Сохранить веб-страницу 
* DELETE Удалить веб-страницу 
* TRACE Отобразить входящий запрос 
* CONNECT Подключиться через прокси 
* OPTIONS Параметры запроса страницы

В ответ на каждый запрос включается строка состояния, часто вместе с до-полнительной информацией (например, веб-страница целиком или ее часть). Эта строка может содержать трехразрядный код состояния, сообщающий об успешном выполнении запроса или о причинах неудачи. Первый разряд предназначен для разделения всех ответов на пять основных групп.

* 1xx информация 100 = сервер согласен обрабатывать запросы клиента
* 2xx Успех 200 = запрос успешно обработан; 204 = содержимое отсутствует
* 3xx Перенаправление 301 = страница перемещена; 304 = кэшированная страница все еще доступна
* 4xx Ошибка клиента 403 = ошибка доступа; 404 = страница не найдена 
* 5xx Ошибка сервера 500 = внутренняя ошибка сервера; 503 = попробуйте еще раз позднее

=== Пример обработки запроса

https://fcc.gov/ 

Этот URL-адрес включает в себя три элемента: протокол (https), DNS-имя хоста (fcc.gov) и имя пути (/), которое веб-сервер часто воспринимает как не-который индексный объект по умолчанию.

Когда пользователь выбирает гиперссылку, браузер выполняет ряд действий для загрузки той страницы, на которую она указывает. Рассмотрим последова-тельность действий при активации ссылки в нашем примере:

1. Браузер определяет URL-адрес (исходя из того, какой элемент страницы выбрал пользователь).
2. Браузер запрашивает у службы DNS IP-адрес сервера fcc.gov.
3. DNS выдает в качестве ответа адрес 23.1.55.196.
4. Браузер устанавливает TCP-соединение с этим IP-адресом; поскольку при этом применяется HTTPS, защищенная версия HTTP , TCP-соединение по умолчанию устанавливается с портом 443 (а не со стандартным портом 80 протокола HTTP , который сегодня используется все реже).
5. Браузер отправляет HTTPS-запрос на получение страницы //, которую веб-сервер обычно интерпретирует как некую индексную страницу (например, index.html, index.php и т. п., как указано в конфигурации веб-сервера хоста fcc.gov).
6. Сервер отправляет страницу как HTTPS-ответ, например, в виде файла /index.html, если таковой определен как индексный объект по умолчанию.
7. Если страница содержит URL-адреса, которые нужно отобразить, то браузер получает их таким же способом. В нашем случае эти URL-адреса содержат ряд встроенных изображений, также загружаемых с данного сервера, встро-енные объекты с сайта gstatic.com и скрипт с сайта google-analytics.com (а также с ряда других доменов, которые здесь не показаны).
8. Браузер отображает страницу /index.html в том виде, в каком она представ-лена на рисунке (прикреплю??)
9. Если в течение некоторого времени на те же серверы не поступает других запросов, TCP-соединения обрываются

== Протокол передачи файлов  ftp footnote:[wiki]
FTP (англ. File Transfer Protocol) — один из старейших протокол передачи файлов по сети 1971. на сегодняшний день широко используется для распространения ПО и доступа к удалённым хостам. В отличие от TFTP, гарантирует передачу (либо выдачу ошибки) за счёт применения квитируемого протокола.

Протокол построен на архитектуре «клиент-сервер» и использует разные сетевые соединения для передачи команд и данных между клиентом и сервером. Пользователи FTP могут пройти аутентификацию, передавая логин и пароль открытым текстом, или же, если это разрешено на сервере, они могут подключиться анонимно. Можно использовать протокол SSH для безопасной передачи, шифрующей (скрывающей) логин и пароль, а также содержимое файла.

=== Сравнение с html

|=======
|Свойство	|FTP	|HTTP
|Встроена аутентификация пользователей	|Да	|Нет
|Изначально предусмотрен для передачи	|Больших двоичных файлов	|Небольших текстовых файлов
|Модель соединения	|Двойное подключение	|Одиночное подключение
|Поддерживает текстовый и двоичный режимы передачи	|Да	|Нет
|Поддерживает указание типов передаваемых данных (MIME заголовки)	|Нет	|Да
|Поддерживает операции над файловой системой (mkdir, rm, rename, и т. д.)	|Да	|Нет

|=======

== язык разметки гипертекста HTML

HTML (HyperText Markup Language — язык разметки гипертекста)

Язык разметки позволяет отделить контент от способа его представления. Свойства отображения текста пишутся на языке CSS (Cascading Style Sheets — каскадные таблицы стилей).

== разработка WEB-страниц 
Страница может быть

* статичная (static page) -- это документ, который всегда отображается одинаково.
* динамическая страница (dynamic page) --  создается по требованию программы или сама содержит какую-либо программу.

=== Обработка динамических страниц

==== Рендеринг на стороне сервера

Когда пользователь активирует в форме ссылку (например, чтобы купить некий товар), серверу по указанному в форме URL-адресу отправляется запрос с введенной пользователем информацией. Эти данные должны быть переданы скрипту или программе для обработки. Тогда вместо доступа к файлам на сервере, ссылка обрабатывается иным образом (например, для заказа товара).

Варианты реализации:

* через общий шлюзовый интерфейс (Common Gateway Interface, CGI)
* Встраивать скрипты в html код и рендерить его на сервере (например, используя php, django?)
* Другое, единого стандарта нет

Они могут принимать входящую информацию из форм, осуществлять поиск по одной или нескольким базам данных и в качестве результата генерировать HTML-страницы. 

==== Рендеринг на стороне клиента
по-зволяет напрямую взаимодействовать с пользователем, например реагировать на движения мыши. Для этих целей необходимы скрипты, внедренные в HTML-страницы и выполняющиеся на клиентском устройстве

Начиная с HTML 4.0, появилась возможность включать скрипты такого типа с помощью тега <script>

Для описания таких скриптом используется JavaScript. После нажатия кнопки подтверждения браузер сам ин-терпретирует содержащийся на странице JavaScript-код. Вся работа произво-дится локально, внутри браузера, без какого-либо взаимодействия с сервером.


== WWW-серверы
Сервер в основном цикле сервер выполняет следующие действия:

1. Принимает входящее TCP-соединение от клиента (браузера).
2. Получает путь к странице, являющийся именем запрашиваемого файла.
3. Получает файл (с диска)/выполняет обработку динамической страницы. 
4. Высылает содержимое файла клиенту.
5. Разрывает TCP-соединение.

==== Оптимизации 

* кэшировать в памяти n последних запрошенных файлов
* Параллельную обработку запросов также можно осуществить с помощью многопоточных (multithreaded) серверов. 

 В одной из реализаций такого подхода сервер состоит из интерфейсного модуля, принимающего все входящие запро-сы, и k обрабатывающих модулей. Все k + 1 потоков принадлежат одному и тому же процессу, поэтому у обрабатывающих модулей есть доступ к кэшу в адресном пространстве процесса.

современные веб-архитектуры разделяются на интерфейсную («фронтенд») и серверную («бэ-кенд») части. 

 Интерфейсный веб-сервер часто называют обратным прокси-сервером (reverse proxy), поскольку он как посредник («прокси») извлекает содержимое из других серверов (обычно относящихся к серверной части) и доставляет эти объекты клиенту. Слово «обратный» указывает на то, что он действует от имени сервера, а не клиента.
