= 7. Передача данных по сети

== Удаленный доступ к ресурсам сети. 

== Организация электронной почты 
Система e-mail состоит из двух подсистем: 

=== пользовательских агентов (user agents)

это программа, предоставляющая графический интерфейс (а иногда интерфейс, основанный на тексте или командах), через ко-торый пользователи взаимодействуют с системой электронной почты.

* позволяют пользова-телям читать и отправлять письма

=== Агенты передачи сообщений (message transfer agents)
неформально можно называть почтовыми серверами (mail servers)

Агенты передачи сообщений, как правило, являются системными процессами, которые работают в фоновом режиме на устройствах почтовых серверов и всегда должны быть доступны. 

Они автоматически перемещают почтовые сообщения в системе от отправителя к получателю с помощью протокола SMTP

* пересылают письма от отправителя к получателю; 

 Агенты передачи также применяют списки рассылки (mailing lists), чтобы доставлять идентичные копии сообщений всем получателям в списке. Среди других полезных функций можно назвать следующие: копия письма, скры-тая копия, высокий приоритет письма, секретная (то есть зашифрованная) почта, доставка сообщения альтернативному получателю (если основной временно недоступен), а также возможность предоставить доступ к почте своему секретарю.

=== Почтовые ящики

Соединение пользовательских агентов и агентов передачи сообщений обеспечивают почтовые ящики и стандартный формат почтовых сообщений. 

Почтовые ящики (mailboxes) хранят доставленную почту. Они обслужива-ются почтовыми серверами. Пользовательские агенты просто предоставляют людям возможность увидеть содержимое их почтовых ящиков. Для этого агент отправляет команды почтовым серверам и получает возможность управлять почтовыми ящиками (проверять содержимое, удалять сообщения и т. д.). 

При такой архитектуре один пользователь может использовать различные пользовательские агенты на разных устройствах, чтобы получить доступ к одному и тому же почтовому ящику.

=== smtp

В интернете для доставки электронной почты компьютер-источник уста-навливает TCP-соединение с портом 25 компьютера-получателя. 

Этот порт прослушивается почтовым сервером, который поддерживает простой протокол передачи электронной почты (Simple Mail Transfer Protocol, SMTP). Есть два способа передачи сообщений

У становив TCP-соединение с портом 25, передающий компьютер, выступающий в роли клиента, ждет запроса принимающего компьютера, рабо-тающего в режиме сервера. Сервер начинает диалог с того, что отсылает тексто-вую строку с его идентификатором и информацией о том, готов ли он к приему почты. Если нет, клиент разрывает соединение и повторяет попытку позднее.

Если сервер готов принимать почту, клиент сообщает, от кого она поступила и кому предназначается. Если такой получатель существует на этом направлении, сервер дает клиенту добро на пересылку сообщения. Тогда клиент отправляет его, а сервер подтверждает его получение. Контрольные суммы не проверяются, так как TCP обеспечивает надежный байтовый поток. Если у отправителя есть еще почта, она также отсылается. После передачи всей почты в обоих направлениях соединение разрывается.

=== недастатки smtp

* не предусматривает аутентификации. Это означает, что команда FROM в нашем примере может отобразить какой угодно адрес отправителя, что крайне удобно для рассылки спама
* сообщения в кодировке ASCII, но не бинарные данные.
* отсылает сообщение в незашифрованном виде

=== Extended SMTP, ESMTP
Клиенты, желающие применить ESMTP, на первом этапе высылают EHLO вместо HELO. Если этот вариант отвергается, сервер работает с обычным SMTP , а пользователь должен идти по стандартному пути. Если EHLO принимается, сервер сообщает, какие расширения он поддерживает. После этого клиент может использовать любое из них.

=== Окончательная доставка сообщения 
SMTP основан на механизме push. Для передачи сообщения ему необходимо со-единение с удаленным сервером. Поэтому smpt не может доставлять сообщения на клиент, который может быть не подключен к сети.

Поэтому на этапе окончательной доставки чаще всего используется протокол доступа к электронной почте (Internet Mail Access Protocol, IMAP )	

 Это улучшенная версия протокола почтового отделения версии 3 (Post Office Protocol, version 3, POP3)

=== Веб-почта 

Популярной альтернативой IMAP и SMTP в деле предоставления почтовых ус-луг стало использование веб-интерфейса для отправки и получения сообщений. 

Широко применяются такие системы веб-почты (Webmail), как Google Mail, Microsoft Hotmail и Yahoo! Mail. Веб-служба электронной почты — это пример программного обеспечения (в данном случае почтового агента пользователя), которое предоставляется как интернет-служба.

В такой системе провайдер принимает сообщения для пользователей при помощи SMTP через порт 25. В этой модели подача почты происходит при использовании обычных веб-протоколов с отправкой данных по URL.


== Организация телеконференций. 


== Протоколы передачи файлов FTP и HTTP, 

== язык разметки гипертекста HTML, 

== разработка WEB-страниц,

== WWW-серверы.
